# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 501a9a33cf531cbe29d40eeebfed4e19f1f48b74beff704c881c4f0a0d3b0187bef3a3279acddbeb3a5e5c9c1bf8ea158798173ae221a7c548116f43d617707f

test:
  secret_key_base: caf36d758d0ce76d01bf3656fa879c6d61e52fcd615765bf21bdeeb9d1651442333be06f7f0848c0a36a990a9eb3e26fcd19a16d1ead5c581a9082db2100426a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
